---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: customers-service
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vets-service
  name: vets-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: vets-service
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: visits-service
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
    nodePort: {{ .Values.gatw.nodePort }}

  selector:
    app: api-gateway
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prom-app-metric
  namespace: {{ .Values.namespace }}
  labels:
    app: prom-app-metric
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    nodePort: {{ .Values.prom.nodePort }}
  selector:
    app: prom-app-metric
