---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: customers-service
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vets-service
  name: vets-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: vets-service
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: visits-service
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: {{ .Values.namespace }}
  annotations:
    # Note that the backend talks over HTTP.
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    # TODO: Fill in with the ARN of your certificate.
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: {{ .Values.certarn }}
    # Only run SSL on the port named "https" below.
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  ports:
  - name: "http"
    port: 80
    targetPort: 8080
    nodePort: {{ .Values.gatw.nodePort }}
  - name: "https"
    port: 443
    targetPort: 8080
  selector:
    app: api-gateway
  type: LoadBalancer
status:
  loadBalancer: {}
---

