apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-mysql
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  mysql-root-password: {{ .Values.petclinic.bdpwdroot }}
  mysql-user-password: {{ .Values.petclinic.bdpwd }}
