apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
             secretKeyRef:
               name: petclinic-db-mysql
               key: mysql-root-password
        - name: MYSQL_DATABASE
          value: {{ .Values.petclinic.dbname }}
        - name: MYSQL_USER
          value: {{ .Values.petclinic.dbuser }}
        - name: MYSQL_PASSWORD
          valueFrom:
             secretKeyRef:
               name: petclinic-db-mysql
               key: mysql-user-password
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
